version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test:
    docker:
      - image: cimg/node:16.16
    steps:
      - run:
          name: Install Rust and circom
          command: |
            curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
            source "$HOME/.cargo/env"
            git clone https://github.com/iden3/circom.git
            cd circom
            cargo build --release
            cargo install --path circom
      - run:
          name: Check Circom
          command: circom --help
      - checkout
      - node/install-packages:
          pkg-manager: "yarn"
      - run:
          name: Run tests
          command: yarn test

workflows:
  test:
    jobs:
      - test

