version: 2.1

jobs:
  test:
    docker:
      - image: goodguyankit/circom-node:1.0
    steps:
      - checkout:
          path: my-project
      - run:
          name: Install dependencies
          command: |
            cd my-project
            yarn install
      - run:
          name: Run tests
          command: |
            cd my-project
            yarn test

workflows:
  test:
    jobs:
      - test
