version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test:
    docker:
      - image: goodguyankit/circom-node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: "yarn"
      - run:
          name: Run tests
          command: yarn test

workflows:
  test:
    jobs:
      - test

